### ISSUE TITLE
Combining replicates

### ISSUE THREAD

**Issue by ericmalekos** [de-Boer-Lab/MAUDE#3]
Hello, I'm using MAUDE to analyze a screen sorted into 25% low GFP and 25% high GFP across 3 replicates. I followed the tutorials and believe I have taken the analogous steps through to the point where "findGuideHitsAll" is called.

My plan was then to call "elementLevelStats", treating each guide as an element and determining which are significantly found in high/low samples using the information from all of the replicates, but it seems that this only considers each replicate separately? For example
```
> elementLevelStats[elementLevelStats$sgRNA=="AIM2_g1", ] 
expt numGuides   sgRNA    stoufferZ        meanZ significanceZ   p.value       FDR
    A         1 AIM2_g1  0.021525793  0.021525793     0.2167735 0.4141924 0.9999564
    B         1 AIM2_g1 -0.071431605 -0.071431605    -0.9320675 0.1756508 0.9986673
    C         1 AIM2_g1 -0.009551456 -0.009551456    -0.1174384 0.4532563 0.9991716
```
It appears each replicate, A/B/C is represented separately, can this information be combined so as to make a single claim (i.e. FDR) across replicates?

Supplementary info:
```
> binStats
  Bin binStartQ binEndQ fraction  binStartZ    binEndZ expt
1  lo     0.001   0.250    0.249 -3.0902323 -0.6744898    A
2  hi     0.749   0.999    0.250  0.6713462  3.0902323    A
3  lo     0.001   0.250    0.249 -3.0902323 -0.6744898    B
4  hi     0.749   0.999    0.250  0.6713462  3.0902323    B
5  lo     0.001   0.250    0.249 -3.0902323 -0.6744898    C
6  hi     0.749   0.999    0.250  0.6713462  3.0902323    C

# call to elementLevelStats:
elementLevelStats = getElementwiseStats(experiments = unique(binReadMat["expt"]),
                                             normNBSummaries = guideLevelStats,
                                             negativeControl = "isNontargeting",
                                             elementIDs="sgRNA",tails="both")
```

**Comment by Carldeboer** [comment]
You are correct that each replicate is analyzed separately. 
Combining the replicates afterwards can be done a number of different ways. I prefer to look only at effects that are robust in each replicate. For instance, requiring that both replicates show the same sign change relative to untreated. This only makes sense if you have an untreated condition (usually gleaned via non-targeting guides).  In the [CD69 tutorial](https://github.com/de-Boer-Lab/MAUDE/blob/master/vignettes/CD69_tutorial.Rmd) we take this approach (lines 305-312), requiring that both replicates are significant at an FDR of 1% and alter expression in the same way. This is quite stringent since both must be significant at quite a low FDR. Other approaches may be better if you want to be more inclusive at the expense of additional false positives.

Either way, requiring that both changed expression in the same direction is a good idea. An easy way to do this is:
```{R}
# in these examples, I am assuming you have both replicates in a data.frame where each stat is present in conjunction with each replicate in columns (and there are only two replicates, repA and repB
elementStatsBothReplicates$sameDirection = elementStatsBothReplicates$meanZ.repA * elementStatsBothReplicates$meanZ.repB > 0
```
The logic here is that one replicate might show the element is a repressor and the other shows the element as an activator;  since they disagree on the effect, do we believe it? This will mostly happen in cases where neither replicate is significant in isolation (e.g. meanZ estimates are essentially experimental noise).


Alternate ways one might combine replicates to get combined FDRs:


1. Make sure that both replicates are significant, at least to some degree, in isolation. 
```{R}
elementStatsBothReplicates$bothSignificant =  elementStatsBothReplicates$FDR.repA<sqrt(alpha) & elementStatsBothReplicates$FDR.repB<sqrt(alpha) & elementStatsBothReplicates$sameDirection
```
Here, both A and B have to be significant at an FDR of sqrt(10%) for a combined final FDR of ~10%. The logic here is that if one replicate showed a strong effect and the other showed nothing, the effect you are seeing is not replicable. 

2.  I could see some scenarios where this may not be the best option. For instance, if there are enhancers that are active only in some replicates due to cell line-specific or experimental effects and you want to include these. In this case, you might want to be more inclusive and only require that one of them is significant. In this case, you could combine the P.values in a more traditional way, and then re-adjust them. Below does this with the stouffer Z scores instead, which are like a signed P.value. (so we can represent significant up and significant down).

```{R}
#the next line combines the stoufferZ scores for each replicate into one. 
elementStatsBothReplicates$stoufferZ.combined = combineZStouffer( c(  elementStatsBothReplicates$stoufferZ.repA, elementStatsBothReplicates$stoufferZ.repB) )  

# for a two-tailed test, we want Z<0 to be downregulation and Z>0 to be upregulation, so we'll test both
elementStatsBothReplicates$p.value.combined = ifelse(elementStatsBothReplicates$stoufferZ.combined < 0, pnorm(elementStatsBothReplicates$stoufferZ.combined ), pnorm(-elementStatsBothReplicates$stoufferZ.combined )
elementStatsBothReplicates$p.value.combined = elementStatsBothReplicates$p.value.combined *2 #for two-tailed adjustment

#Perform Benjamini-Hochberg FDR correction on these P-values
elementStatsBothReplicates$FDR.combined = p.adjust( elementStatsBothReplicates$p.value.combined, method = "BH")

# require that the FDR is less than alpha and that both replicates showed the same directional change to be considered significant
elementStatsBothReplicates$bothSignificant = elementStatsBothReplicates$FDR.combined <alpha & elementStatsBothReplicates$sameDirection
```

**Comment by ericmalekos** [comment]
Wow excellent response, thank you!

**Comment by ericmalekos** [comment]
> Here, both A and B have to be significant at an FDR of sqrt(10%) for a combined final FDR of ~10%. The logic here is that if one replicate showed a strong effect and the other showed nothing, the effect you are seeing is not replicable.

Statistically naive question: can you point me to a good method for estimating/obtaining the combined of FDR from `n` replicates (rather than just two)?

**Comment by Carldeboer** [comment]
This is just based on multiplying probabilities for independent events. To get the probability of two events both happening, assuming they are independent, is P1*P2.  

An FDR of alpha% means that, any particular hypothesis in your set of "significant" hypotheses at the threshold alpha is a false discovery with a probability of alpha. Assuming your replicates are independent*, the combined probability of the hypotheses you declared are significant at alpha being false discoveries in all n replicates is alpha^n. 

I would look at your data in more detail before you pick an approach for combining replicates. If you have >2 replicates, you can do some more logical things. For instance, if you have 3 replicates and one is a clear outlier, it's probably best to ignore that one. Lots of strange things can happen in experiments. This approach (requiring all to be in the same direction and significant at n_root(alpha)) means that if something went bad in one replicate, you will not consider it significant. If you have only two replicates, then there's no way to tell which is "correct". This also depends on your tolerance for false discoveries. If it is high, then you want to allow more false discoveries to throw out fewer true hypotheses. If your tolerance for false discoveries is low, then you want to be very stringent (e.g. requiring all replicates to agree and be independently significant). This depends on what you are doing. E.g. If I was going to study an enhancer or gene in detail based on the results of this screen, I would want to be darn sure it's not a false discovery.

*This may not be true. For instance, if noise is related to the biological variables. An example is cases where guide abundances are not all equal, guides with lower coverage have higher noise in every replicate.

Another important note: If a hypothesis is true at a FDR of Q=0.1, that does not mean there is a 10% chance of that particular hypothesis being false. The probability of that hypothesis being false can actually be substantially higher. For instance, if the other 90% of hypotheses at FDR=0.1 are clearly significant (FDR~=0 for this 90%), then the remaining 10% are most likely the false discoveries.
