### ISSUE TITLE
Maude use with single bin?

### ISSUE THREAD

**Issue by ericmalekos** [de-Boer-Lab/MAUDE#5]
Hello,

Is there any sensible way to use MAUDE if I only have an upper 20% bin (missing the bottom 20%) and an unsorted background?

**Comment by Carldeboer** [comment]
The short answer is yes, but with only one bin the estimates may be pretty off. 
The following code snippet removes the first 5/6 bins and runs MAUDE using only bin F (10% in this case). I ran it after line 148 in [this file](https://github.com/de-Boer-Lab/MAUDE/blob/master/vignettes/simulated_data_tutorial.Rmd).

```{r}
# get guide-level stats 
guideLevelStatsOneBin = findGuideHitsAllScreens(unique(binReadMat["screen"]), binReadMat[! (colnames(binReadMat) %in% c("A","B","C","D","E") )], binBounds[binBounds$Bin=="F",], sortBins=c("F"))

#get element level stats
elementLevelStatsOneBin = getElementwiseStats(unique(guideLevelStatsOneBin["screen"]),
  guideLevelStatsOneBin, elementIDs="element",tails="upper")

elementLevelStatsOneBin = merge(elementLevelStatsOneBin, groundTruth, by="element")

p = ggplot(elementLevelStatsOneBin, aes(x=meanEffect, y=meanZ, colour=FDR<0.01)) + geom_point()+
  geom_abline(intercept = 0, slope=1) + theme_classic() + scale_colour_manual(values=c("darkgray","red")) + 
  xlab("True effect") + ylab("Inferred effect"); print(p)
```

The reason this doesn't work well with one bin is not a failing of MAUDE, but results from there being multiple explanations for the same data. As an illustrative example, if we have a single bin spanning from 40%-60% of the total distribution (i.e. the middle 20%), we can tell that expression didn't move much if we get a proportional number of reads for the "guide" in that bin (e.g. if the guide is r_{g.l}/R_l of the library, it is r_{g,b}/R_b of the bin). If expression of the guide is skewed to higher expression or to lower expression, the result is the same: fewer reads in this central bin (r_{g.l}/R_l > r_{g,b}/R_b). Increased and decreased expression are equally likely explanations. The same could be said of the top 20% bin, but at more extreme expressions: the guide could be lowly represented in that bin because it has a moderate expression (and the bin skimmed only the top few cells for this guide), or a really high expression (and the bin skimmed only the bottom few cells for this guide). With multiple bins you can resolve this, but with only a single bin, you cannot. 

This can be demonstrated with the following snippet of code, which now uses two bins that together make up the top 20%. Now MAUDE predicts very close to the true expression effect:

```{r}
# get guide-level stats 
guideLevelStatsTwoBins = findGuideHitsAllScreens(unique(binReadMat["screen"]), binReadMat[! (colnames(binReadMat) %in% c("A","B","C","D") )], binBounds[binBounds$Bin%in%c("E","F"),], sortBins=c("E","F"))

#get element level stats
elementLevelStatsTwoBins = getElementwiseStats(unique(guideLevelStatsTwoBins["screen"]),
  guideLevelStatsTwoBins, elementIDs="element",tails="upper")

elementLevelStatsTwoBins = merge(elementLevelStatsTwoBins, groundTruth, by="element")

p = ggplot(elementLevelStatsTwoBins, aes(x=meanEffect, y=meanZ, colour=FDR<0.01)) + geom_point()+
  geom_abline(intercept = 0, slope=1) + theme_classic() + scale_colour_manual(values=c("darkgray","red")) + 
  xlab("True effect") + ylab("Inferred effect"); print(p)

```
